### PR TITLE
BREAKING CHANGE: Only allow setting the temperature to multiples of 100 within the device's accepted range

### LINKED ISSUE #92: Setting temperature as a percentage does not work for all values
Setting your Litra's temperature to a percentage value using the `litra-temperature` CLI or the `setTemperaturePercentage` function does not work reliably.

Based on my testing, it seems that you cannot make set the temperature to _any_ value within your device's supported range. At least from what I'm seeing, it looks like only steps of 100 are supported. The brightness-related features work as expected.

I'd love to have someone else test this to see if it's something specifically wrong with my device. If it isn't, then we can figure out a way forward - either removing the percentage functionality for temperature or "snapping" to the allowed values.

## Reproduction steps

_Note that the allowed temperature range for a Litra Glow is 2700-6500K_

1. Set your Litra Glow's temperature to 0% by running `litra-temperature 0`. You observe a change in the light.
2. Set your Litra Glow's temperature to 10% by running `litra-temperature 10`. Nothing happens.
3. Set your Litra Glow's temperature to 100% by running `litra-temperature 100`. You observe a change in the light.
4. Set your Litra Glow's temperature to 2700K by running `litra-temperature-k 2700`. You observe a change in the light.
5. Set your Litra Glow's temperature to 2799K by running `litra-temperature-k 2799`. Nothing happens.
6. Set your Litra Glow's temperature to 2800K by running `litra-temperature-k 2800`. You observe a (small!) change in the light.

### PR DESCRIPTION
**Pull request by timrogers**
Per #92, it's only possible to set a Litra's temperature to multiples of 100 between the device's minimum and maximum. In practice, if you try to use another value, your device does nothing, but at the moment, this library accepts the input.

This introduces stricter validations in `setTemperatureInKelvin`, throwing an error for unsupported values, and removes the `setTemperaturePercentage` function and `litra-temperature` CLI, since accepting a percentage doesn't really work if many values are not allowed.

Fixes #92.

### CODE REVIEW

File: src/driver.ts [hunk 1]
```diff
@@ -278,7 +250,18 @@ export const getMinimumTemperatureInKelvinForDevice = (device: Device): number =
...
+  return allowedTemperatures[allowedTemperatures.length - 1];
+};
+
+/**
+ * Gets all temperature values in Kelvin supported by a device
+ *
+ * @param {Device} device The device to check the allowed temperatures for
+ * @returns {number[]} The temperature values in Kelvin supported by the device
+ */
+const getAllowedTemperaturesInKelvinForDevice = (device: Device): number[] => {
```
Comment (timrogers) [inline src/driver.ts:263]: I did consider exporting this function - happy to add it later if people want it!

**Comment by timrogers** [comment]
@NMichas What do you think of this solution to #92?

**Comment by NMichas** [comment]
LGTM @timrogers
